apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubemoot-docs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubemoot-docs.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubemoot-docs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubemoot-docs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubemoot-docs.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: docs
          image: {{ include "kubemoot-docs.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            # nginx's pid file and temp paths
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
