apiVersion: v2
name: kubemoot-docs
description: Hugo/Docsy documentation site for the Kubemoot ecosystem
type: application

# This version is set by CI/CD from git tags - DO NOT hardcode
version: 0.17.0-rc.1
appVersion: 0.17.0-rc.1

keywords:
  - kubemoot
  - docs
  - documentation

home: https://github.com/kubemoot/kubemoot-docs
sources:
  - https://github.com/kubemoot/kubemoot-docs

maintainers:
  - name: Kubemoot maintainers
    email: moot@kubemoot.org
